# Request
std_msgs/Header header
gl_interfaces/ImageQueryParams params
sensor_msgs/Image image
---
# Result
std_msgs/Header header
gl_interfaces/ImageQueryParams params
gl_interfaces/ImageQueryResponse response
---
# Feedback
std_msgs/Header header
gl_interfaces/ImageQueryParams params
gl_interfaces/ImageQueryResponse response